"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['gamepage.py']
DATA_FILES = ['black.png', 'grey.png', 'tan.png', 'white.jpg', 'wood.jpg', 'king.png']
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
